spring:
  app:
    name: mohan

info:
  app:
    name: ${spring.application.name}
    description: Very cool Spring Boot application
    version: '1.0'


# Actuator Properties
# Check the list of endpoints available here:
# https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.enabling

management:
  server:
    port: 9001
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: "always"
  endpoints:
    # Disable all JMX endpoints.
    jmx:
      exposure:
        exclude: "*"
    web:
      base-path: "/management"
      cors:
        allowed-origins: "https://example.com"
        allowed-methods: "GET"
      exposure:
        include: "*"
        exclude: "beans"


